apiVersion: apps/v1
kind: Deployment
metadata:
  name: cezzis-com-cocktails-api
  namespace: cezzis
  labels:
    app: cezzis-com-cocktails-api
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "405"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: cezzis-com-cocktails-api
  template:
    metadata:
      labels:
        app: cezzis-com-cocktails-api
        app.kubernetes.io/part-of: cezzis
        app.kubernetes.io/managed-by: argocd
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "cezzis-com-cocktails-api"
        dapr.io/app-port: "7177"
        dapr.io/app-protocol: "http"
        dapr.io/log-level: "info"
        dapr.io/config: "cocktails-api-dapr-config"
        dapr.io/api-token-secret: "cezzis-shared-daprio-dapr-api-token"
        dapr.io/app-token-secret: "cezzis-shared-daprio-app-api-token"
        dapr.io/enable-native-sidecar: "true"
    spec:
      imagePullSecrets:
        - name: acr-pull-secret
      containers:
        - name: cezzis-com-cocktails-api
          image: acrveceusgloshared001.azurecr.io/cocktailsapi
          ports:
            - containerPort: 7177
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: cezzis-com-cocktails-api-config
            - secretRef:
                name: cezzis-com-cocktails-api-secrets
            - secretRef:
                name: cezzis-com-cocktails-api-shared-secrets
          startupProbe:
            httpGet:
              path: /api/v1/health/liveness
              port: 7177
            initialDelaySeconds: 5
            periodSeconds: 3
            timeoutSeconds: 5
            failureThreshold: 40
          readinessProbe:
            httpGet:
              path: /api/v1/health/readiness
              port: 7177
            periodSeconds: 15
            timeoutSeconds: 30
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/v1/health/liveness
              port: 7177
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: shared-pod-data
              mountPath: /app/data
              subPath: cezzis/cezzis-com-cocktails-api
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      initContainers:
        - name: init-data-dir
          image: busybox:1.37
          command: ["sh", "-c", "mkdir -p /pods/cezzis/cezzis-com-cocktails-api"]
          volumeMounts:
            - name: shared-pod-data
              mountPath: /pods
      volumes:
        - name: shared-pod-data
          persistentVolumeClaim:
            claimName: shared-pod-data-pvc
