apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yml
  - external-secrets.yml
  - ../dapr/k8s-prd/
  - deployment.yml
  - service.yml
  - ingress.yml
images:
  - name: acrveceusgloshared001.azurecr.io/cocktailsapi
    newTag: 0.1.171
    newName: acrveceusgloshared001.azurecr.io/cocktailsapi
