apiVersion: dapr.io/v1alpha1
kind: Component

metadata:
  name: secret-store

spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: /components/env-secrets.json